-- H2 Database Initialization Script
-- Converted from seatunnel_mysql.sql, adapted for H2 database syntax

-- Note: H2 in-memory database is automatically created, no need to explicitly create database

-- Data source table
CREATE TABLE IF NOT EXISTS t_seatunnel_datasource
(
    id                BIGINT NOT NULL PRIMARY KEY,
    db_name           VARCHAR(64)   DEFAULT NULL,
    db_type           VARCHAR(64)   DEFAULT NULL,
    original_json     TEXT,
    connection_params TEXT,
    environment       VARCHAR(200)  DEFAULT NULL,
    remark            VARCHAR(2048) DEFAULT NULL,
    conn_status       VARCHAR(24)   DEFAULT NULL,
    create_time       TIMESTAMP     DEFAULT NULL,
    update_time       TIMESTAMP     DEFAULT NULL
);

-- Data source plugin configuration table
CREATE TABLE IF NOT EXISTS t_seatunnel_datasource_plugin_config
(
    id            VARCHAR(32) NOT NULL PRIMARY KEY,
    plugin_type   VARCHAR(50) NOT NULL,
    config_schema TEXT        NOT NULL,
    create_time   TIMESTAMP DEFAULT NULL,
    update_time   TIMESTAMP DEFAULT NULL
);

-- Job definition table
CREATE TABLE IF NOT EXISTS t_seatunnel_job_definition
(
    id                  BIGINT       NOT NULL PRIMARY KEY,
    job_name            VARCHAR(255) NOT NULL,
    job_desc            VARCHAR(500) DEFAULT NULL,
    job_definition_info TEXT         NOT NULL,
    job_version         INT          NOT NULL DEFAULT 1,
    client_id           BIGINT       DEFAULT NULL,
    create_time         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    whole_sync          BOOLEAN      NOT NULL DEFAULT FALSE,
    source_type         VARCHAR(255) DEFAULT NULL,
    sink_type           VARCHAR(255) DEFAULT NULL,
    parallelism         INT          DEFAULT 1,
    source_table        VARCHAR(1024) DEFAULT NULL,
    sink_table          VARCHAR(1024) DEFAULT NULL
);

-- Job instance table
CREATE TABLE IF NOT EXISTS t_seatunnel_job_instance
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_definition_id BIGINT   NOT NULL,
    job_config        TEXT,
    start_time        TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    end_time          TIMESTAMP DEFAULT NULL,
    job_type          VARCHAR(10)  DEFAULT NULL,
    job_status        VARCHAR(255) DEFAULT NULL,
    job_engine_id     VARCHAR(255) DEFAULT NULL,
    log_path          VARCHAR(512) DEFAULT NULL,
    error_message     TEXT,
    run_mode          VARCHAR(100) DEFAULT NULL
);

-- Job metrics table
CREATE TABLE IF NOT EXISTS t_seatunnel_job_metrics
(
    id                      BIGINT NOT NULL PRIMARY KEY,
    job_instance_id         BIGINT NOT NULL,
    pipeline_id             INT    DEFAULT NULL,
    read_row_count          BIGINT DEFAULT 0,
    write_row_count         BIGINT DEFAULT 0,
    read_qps                BIGINT DEFAULT 0,
    write_qps               BIGINT DEFAULT 0,
    read_bytes              BIGINT DEFAULT 0,
    write_bytes             BIGINT DEFAULT 0,
    read_bps                BIGINT DEFAULT 0,
    write_bps               BIGINT DEFAULT 0,
    intermediate_queue_size BIGINT DEFAULT 0,
    lag_count               BIGINT DEFAULT 0,
    loss_rate               DOUBLE DEFAULT 0,
    avg_row_size            BIGINT DEFAULT 0,
    record_delay            BIGINT DEFAULT 0,
    create_time             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    update_time             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    job_definition_id       BIGINT DEFAULT NULL
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_job_instance_id ON t_seatunnel_job_metrics(job_instance_id);
CREATE INDEX IF NOT EXISTS idx_create_time ON t_seatunnel_job_metrics(create_time);
CREATE UNIQUE INDEX IF NOT EXISTS uk_instance_pipeline ON t_seatunnel_job_metrics(job_instance_id, pipeline_id);

-- Job schedule table
CREATE TABLE IF NOT EXISTS t_seatunnel_job_schedule
(
    id                 VARCHAR(32)  NOT NULL PRIMARY KEY,
    job_definition_id  VARCHAR(32)  NOT NULL,
    cron_expression    VARCHAR(50)  NOT NULL,
    schedule_status    VARCHAR(20)  DEFAULT 'STOPPED',
    last_schedule_time TIMESTAMP    DEFAULT NULL,
    next_schedule_time TIMESTAMP    DEFAULT NULL,
    schedule_config    TEXT,
    create_time        TIMESTAMP    DEFAULT NULL,
    update_time        TIMESTAMP    DEFAULT NULL
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_task_definition_id ON t_seatunnel_job_schedule(job_definition_id);
CREATE INDEX IF NOT EXISTS idx_schedule_status ON t_seatunnel_job_schedule(schedule_status);

-- Stream job definition table
CREATE TABLE IF NOT EXISTS t_seatunnel_stream_job_definition
(
    id                  BIGINT       NOT NULL PRIMARY KEY,
    job_name            VARCHAR(255) NOT NULL,
    job_desc            VARCHAR(512) DEFAULT NULL,
    job_definition_info TEXT,
    job_type            VARCHAR(50)  NOT NULL,
    job_version         INT          NOT NULL DEFAULT 1,
    client_id           BIGINT       NOT NULL,
    parallelism         INT          NOT NULL DEFAULT 1,
    schedule_status     VARCHAR(50)  DEFAULT 'OFFLINE',
    source_type         VARCHAR(100) DEFAULT NULL,
    source_table        VARCHAR(255) DEFAULT NULL,
    sink_type           VARCHAR(100) DEFAULT NULL,
    sink_table          VARCHAR(255) DEFAULT NULL,
    create_time         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_time         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    plugin_name         VARCHAR(100) DEFAULT NULL
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_client_id ON t_seatunnel_stream_job_definition(client_id);
CREATE INDEX IF NOT EXISTS idx_job_name ON t_seatunnel_stream_job_definition(job_name);
CREATE INDEX IF NOT EXISTS idx_schedule_status ON t_seatunnel_stream_job_definition(schedule_status);

-- CDC server IDs table
CREATE TABLE IF NOT EXISTS t_seatunnel_cdc_server_ids
(
    server_id    INT NOT NULL PRIMARY KEY,
    job_id       VARCHAR(64) DEFAULT NULL,
    allocated_at TIMESTAMP   DEFAULT NULL
);

-- Create unique index
CREATE UNIQUE INDEX IF NOT EXISTS uq_job_jobid_server ON t_seatunnel_cdc_server_ids(job_id, server_id);

-- User table
CREATE TABLE IF NOT EXISTS t_seatunnel_user (
    id            INT NOT NULL PRIMARY KEY,
    user_name     VARCHAR(64) DEFAULT NULL,
    user_password VARCHAR(64) DEFAULT NULL,
    user_type     INT         DEFAULT NULL,
    email         VARCHAR(64) DEFAULT NULL,
    phone         VARCHAR(11) DEFAULT NULL,
    create_time   TIMESTAMP   DEFAULT NULL,
    update_time   TIMESTAMP   DEFAULT NULL,
    state         BOOLEAN     DEFAULT TRUE
);

-- Insert default user
MERGE INTO t_seatunnel_user KEY(id) 
VALUES(1, 'admin', 'e10adc3949ba59abbe56e057f20f883e', 0, '295227940@qq.com', '15002344940', NULL, NULL, TRUE);

-- Session table
CREATE TABLE IF NOT EXISTS t_seatunnel_session (
   id              VARCHAR(64) NOT NULL PRIMARY KEY,
   user_id         INT         DEFAULT NULL,
   ip              VARCHAR(45) DEFAULT NULL,
   last_login_time TIMESTAMP   DEFAULT NULL
);

-- ============================
-- Quartz Scheduler Tables (H2 Compatible Version)
-- ============================

-- BLOB triggers table
CREATE TABLE IF NOT EXISTS QRTZ_BLOB_TRIGGERS
(
    sched_name    VARCHAR(120) NOT NULL,
    trigger_name  VARCHAR(200) NOT NULL,
    trigger_group VARCHAR(200) NOT NULL,
    blob_data     BLOB,
    PRIMARY KEY (sched_name, trigger_name, trigger_group)
);

-- Calendars table
CREATE TABLE IF NOT EXISTS QRTZ_CALENDARS
(
    sched_name    VARCHAR(120) NOT NULL,
    calendar_name VARCHAR(200) NOT NULL,
    calendar      BLOB         NOT NULL,
    PRIMARY KEY (sched_name, calendar_name)
);

-- Cron triggers table
CREATE TABLE IF NOT EXISTS QRTZ_CRON_TRIGGERS
(
    sched_name      VARCHAR(120) NOT NULL,
    trigger_name    VARCHAR(200) NOT NULL,
    trigger_group   VARCHAR(200) NOT NULL,
    cron_expression VARCHAR(200) NOT NULL,
    time_zone_id    VARCHAR(80)  DEFAULT NULL,
    PRIMARY KEY (sched_name, trigger_name, trigger_group)
);

-- Fired triggers table
CREATE TABLE IF NOT EXISTS QRTZ_FIRED_TRIGGERS
(
    sched_name        VARCHAR(120) NOT NULL,
    entry_id          VARCHAR(95)  NOT NULL,
    trigger_name      VARCHAR(200) NOT NULL,
    trigger_group     VARCHAR(200) NOT NULL,
    instance_name     VARCHAR(200) NOT NULL,
    fired_time        BIGINT       NOT NULL,
    sched_time        BIGINT       NOT NULL,
    priority          INT          NOT NULL,
    state             VARCHAR(16)  NOT NULL,
    job_name          VARCHAR(200) DEFAULT NULL,
    job_group         VARCHAR(200) DEFAULT NULL,
    is_nonconcurrent  VARCHAR(1)   DEFAULT NULL,
    requests_recovery VARCHAR(1)   DEFAULT NULL,
    PRIMARY KEY (sched_name, entry_id)
);

-- Job details table
CREATE TABLE IF NOT EXISTS QRTZ_JOB_DETAILS
(
    sched_name        VARCHAR(120) NOT NULL,
    job_name          VARCHAR(200) NOT NULL,
    job_group         VARCHAR(200) NOT NULL,
    description       VARCHAR(250) DEFAULT NULL,
    job_class_name    VARCHAR(250) NOT NULL,
    is_durable        VARCHAR(1)   NOT NULL,
    is_nonconcurrent  VARCHAR(1)   NOT NULL,
    is_update_data    VARCHAR(1)   NOT NULL,
    requests_recovery VARCHAR(1)   NOT NULL,
    job_data          BLOB,
    PRIMARY KEY (sched_name, job_name, job_group)
);

-- Locks table
CREATE TABLE IF NOT EXISTS QRTZ_LOCKS
(
    sched_name VARCHAR(120) NOT NULL,
    lock_name  VARCHAR(40)  NOT NULL,
    PRIMARY KEY (sched_name, lock_name)
);

-- Paused trigger groups table
CREATE TABLE IF NOT EXISTS QRTZ_PAUSED_TRIGGER_GRPS
(
    sched_name    VARCHAR(120) NOT NULL,
    trigger_group VARCHAR(200) NOT NULL,
    PRIMARY KEY (sched_name, trigger_group)
);

-- Scheduler state table
CREATE TABLE IF NOT EXISTS QRTZ_SCHEDULER_STATE
(
    sched_name        VARCHAR(120) NOT NULL,
    instance_name     VARCHAR(200) NOT NULL,
    last_checkin_time BIGINT       NOT NULL,
    checkin_interval  BIGINT       NOT NULL,
    PRIMARY KEY (sched_name, instance_name)
);

-- Simple triggers table
CREATE TABLE IF NOT EXISTS QRTZ_SIMPLE_TRIGGERS
(
    sched_name      VARCHAR(120) NOT NULL,
    trigger_name    VARCHAR(200) NOT NULL,
    trigger_group   VARCHAR(200) NOT NULL,
    repeat_count    BIGINT       NOT NULL,
    repeat_interval BIGINT       NOT NULL,
    times_triggered BIGINT       NOT NULL,
    PRIMARY KEY (sched_name, trigger_name, trigger_group)
);

-- Simple property triggers table
CREATE TABLE IF NOT EXISTS QRTZ_SIMPROP_TRIGGERS
(
    sched_name    VARCHAR(120)   NOT NULL,
    trigger_name  VARCHAR(200)   NOT NULL,
    trigger_group VARCHAR(200)   NOT NULL,
    str_prop_1    VARCHAR(512)   DEFAULT NULL,
    str_prop_2    VARCHAR(512)   DEFAULT NULL,
    str_prop_3    VARCHAR(512)   DEFAULT NULL,
    int_prop_1    INT            DEFAULT NULL,
    int_prop_2    INT            DEFAULT NULL,
    long_prop_1   BIGINT         DEFAULT NULL,
    long_prop_2   BIGINT         DEFAULT NULL,
    dec_prop_1    DECIMAL(13, 4) DEFAULT NULL,
    dec_prop_2    DECIMAL(13, 4) DEFAULT NULL,
    bool_prop_1   VARCHAR(1)     DEFAULT NULL,
    bool_prop_2   VARCHAR(1)     DEFAULT NULL,
    PRIMARY KEY (sched_name, trigger_name, trigger_group)
);

-- Triggers table
CREATE TABLE IF NOT EXISTS QRTZ_TRIGGERS
(
    sched_name     VARCHAR(120) NOT NULL,
    trigger_name   VARCHAR(200) NOT NULL,
    trigger_group  VARCHAR(200) NOT NULL,
    job_name       VARCHAR(200) NOT NULL,
    job_group      VARCHAR(200) NOT NULL,
    description    VARCHAR(250) DEFAULT NULL,
    next_fire_time BIGINT       DEFAULT NULL,
    prev_fire_time BIGINT       DEFAULT NULL,
    priority       INT          DEFAULT NULL,
    trigger_state  VARCHAR(16)  NOT NULL,
    trigger_type   VARCHAR(8)   NOT NULL,
    start_time     BIGINT       NOT NULL,
    end_time       BIGINT       DEFAULT NULL,
    calendar_name  VARCHAR(200) DEFAULT NULL,
    misfire_instr  SMALLINT     DEFAULT NULL,
    job_data       BLOB,
    PRIMARY KEY (sched_name, trigger_name, trigger_group)
);

-- Foreign key constraints
ALTER TABLE QRTZ_CRON_TRIGGERS ADD CONSTRAINT IF NOT EXISTS FK_QRTZ_CRON_TRIGGERS 
    FOREIGN KEY (sched_name, trigger_name, trigger_group) 
    REFERENCES QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group);

ALTER TABLE QRTZ_SIMPLE_TRIGGERS ADD CONSTRAINT IF NOT EXISTS FK_QRTZ_SIMPLE_TRIGGERS 
    FOREIGN KEY (sched_name, trigger_name, trigger_group) 
    REFERENCES QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group);

ALTER TABLE QRTZ_SIMPROP_TRIGGERS ADD CONSTRAINT IF NOT EXISTS FK_QRTZ_SIMPROP_TRIGGERS 
    FOREIGN KEY (sched_name, trigger_name, trigger_group) 
    REFERENCES QRTZ_TRIGGERS(sched_name, trigger_name, trigger_group);

ALTER TABLE QRTZ_TRIGGERS ADD CONSTRAINT IF NOT EXISTS FK_QRTZ_TRIGGERS 
    FOREIGN KEY (sched_name, job_name, job_group) 
    REFERENCES QRTZ_JOB_DETAILS(sched_name, job_name, job_group);