package org.apache.seatunnel.web.api.service;

import com.baomidou.mybatisplus.extension.service.IService;
import lombok.NonNull;
import org.apache.seatunnel.web.common.bean.po.SeatunnelJobMetricsPO;
import org.apache.seatunnel.web.common.bean.vo.OverviewChartsVO;
import org.apache.seatunnel.web.common.bean.vo.OverviewSummaryVO;
import org.apache.seatunnel.web.common.enums.TimeRange;

import java.util.List;
import java.util.Map;

/**
 * Service responsible for managing and querying SeaTunnel job metrics.
 *
 * <p>This service provides access to runtime metrics generated by the
 * execution engine during job execution. These metrics are typically
 * collected periodically and stored for monitoring, visualization,
 * and historical analysis.</p>
 *
 * <p>Main responsibilities include:</p>
 * <ul>
 *     <li>Fetching runtime metrics from the execution engine</li>
 *     <li>Persisting metrics into the database</li>
 *     <li>Providing aggregated metrics for dashboard overview</li>
 *     <li>Generating time-based chart data for monitoring UI</li>
 * </ul>
 */
public interface SeaTunnelJobMetricsService extends IService<SeatunnelJobMetricsPO> {

    /**
     * Retrieves job metrics from the execution engine.
     *
     * <p>The returned map is keyed by metric identifier (for example,
     * vertex ID or metric type depending on the implementation).</p>
     *
     * @param jobEngineId unique identifier of the job in the execution engine
     * @return map of metrics indexed by metric identifier
     */
    Map<Integer, SeatunnelJobMetricsPO> getJobMetricsFromEngineMap(
            @NonNull Long jobEngineId
    );

    /**
     * Persists a batch of job metrics into the database.
     *
     * <p>This method is typically invoked by a scheduler or
     * metrics collector that periodically fetches metrics
     * from the execution engine.</p>
     *
     * @param metricsList list of metrics to store
     */
    void saveMetricsBatch(@NonNull List<SeatunnelJobMetricsPO> metricsList);

    /**
     * Returns aggregated overview statistics for the dashboard.
     *
     * <p>The summary typically includes metrics such as:</p>
     * <ul>
     *     <li>Total number of jobs</li>
     *     <li>Running jobs</li>
     *     <li>Failed jobs</li>
     *     <li>Completed jobs</li>
     * </ul>
     *
     * @param timeRange time window for aggregation
     * @param taskType optional task type filter
     * @return aggregated overview statistics
     */
    OverviewSummaryVO summary(TimeRange timeRange, String taskType);

    /**
     * Returns time-series metrics for dashboard charts.
     *
     * <p>This method is used to generate chart data such as
     * job counts, throughput trends, or failure rates
     * within a given time range.</p>
     *
     * @param timeRange time window for chart generation
     * @param taskType optional task type filter
     * @return chart-ready data structure for visualization
     */
    OverviewChartsVO charts(TimeRange timeRange, String taskType);
}