server:
  port: 9527
  tomcat:
    accept-count: 1000
    max-connections: 10000

seatunnel:
  client:
    base-url: http://192.168.1.115:8080
    context-path:
    connect-timeout-ms: 2000
    read-timeout-ms: 10000

spring:
  profiles:
    active: mysql
  banner:
    charset: UTF-8
  jackson:
    time-zone: GMT+8
    date-format: "yyyy-MM-dd HH:mm:ss"
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  messages:
    basename: i18n/messages
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.113:3306/seatunnel_web?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 123456
    hikari:
      connection-test-query: select 1
      pool-name: seatunnel-web
  application:
    name: seatunnel-web
  main:
    allow-bean-definition-overriding: true
  ai:
    deepseek:
      api-key: sk-****
      base-url: "https://api.deepseek.com"
      chat:
        options:
          model: deepseek-chat
      embedding:
        enabled: false

  quartz:
    auto-startup: false
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    properties:
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.jobStore.tablePrefix: QRTZ_
      org.quartz.jobStore.acquireTriggersWithinLock: true
      org.quartz.scheduler.instanceName: seatunnel-web
      org.quartz.threadPool.class: org.apache.seatunnel.web.api.quartz.QuartzZeroSizeThreadPool
      org.quartz.jobStore.useProperties: false
      org.quartz.jobStore.misfireThreshold: 60000
      org.quartz.scheduler.makeSchedulerThreadDaemon: true
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.clusterCheckinInterval: 5000
      org.quartz.scheduler.batchTriggerAcquisitionMaxCount: 25


logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    enabled-by-default: false

# Mybatis-plus configuration, you don't need to change it
mybatis-plus:
  mapper-locations: classpath:org/apache/seatunnel/web/dao/mapper/*Mapper.xml
  type-aliases-package: org.apache.seatunnel.web.dao.entity
  configuration:
    cache-enabled: false
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL
  global-config:
    db-config:
      id-type: auto
    banner: false